apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secret
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: backstage-secret
  data:
    - secretKey: BACKEND_SECRET
      remoteRef:
        key: backstage-secret-source
        property: BACKEND_SECRET
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: backstage-keycloak-secret-source
        property: clientSecret
    - secretKey: GITHUB_PAT
      remoteRef:
        key: backstage-github-app-source
        property: githubPat
    - secretKey: GITHUB_OAUTH_CLIENT_ID
      remoteRef:
        key: backstage-github-app-source
        property: githubOauthClientId
    - secretKey: GITHUB_OAUTH_CLIENT_SECRET
      remoteRef:
        key: backstage-github-app-source
        property: githubOauthClientSecret
    - secretKey: ARGOCD_TOKEN
      remoteRef:
        key: backstage-secret-source
        property: ARGOCD_TOKEN
