apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: user-app-minio-backup-secret
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  namespaceSelector:
    matchLabels:
      app-type: user-app
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: kubernetes-store
      kind: ClusterSecretStore
    target:
      name: minio-backup-secret
    data:
      - secretKey: ACCESS_KEY_ID
        remoteRef:
          key: minio-backup-secret-source
          property: ACCESS_KEY_ID
      - secretKey: ACCESS_SECRET_KEY
        remoteRef:
          key: minio-backup-secret-source
          property: ACCESS_SECRET_KEY
