apiVersion: v1
kind: Secret
metadata:
    name: backstage-github-app-source
    namespace: platform-secrets
type: Opaque
stringData:
    githubOauthClientId: ENC[AES256_GCM,data:SfylOTe5HGIruE0YHodGDyWTCiw=,iv:53XXFBF5Li71w3Iz00qCptFLis9swPFPVuZn4Tjm18c=,tag:QPQMaMv7T3LfZpvGnkotvA==,type:str]
    githubOauthClientSecret: ENC[AES256_GCM,data:c+IvFf8Im39PGh4vyUpenzh2NIUoRLLHBcWens4alrdljXkRpFql4g==,iv:rTGw5LkYZHQJjPqsrAORgDAITlQFYk4R1ebYKypbDiY=,tag:7k0TneYRmDRmQwo5ui59EA==,type:str]
    githubPat: ENC[AES256_GCM,data:sZ7ycoYDBBQefLrB8RK96GhVpZtE+OdWKYjwYVl5ecireI7jCuY/2GQXGbg0S4ndCGuDXZ5gJLiUcnZ6yU8i59VfuKQYVQmVV4V6o5EC7d9cNlONojh7BilvA3uU,iv:mSP4k58yE0uhJQ6BDwXXhluwsOZRTcTFmrEMvcwBK24=,tag:pe/aNLr4qJqCfBL/unbm1w==,type:str]
sops:
    age:
        - recipient: age1unp3mcue0u65eu28ls4l037jmn3umv6fusa7ggjeduep59tsvussxdurgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRWlIc2ZwNjdyVGZsRGZU
            WXU1VDRRaHFUYzRDS0tqQnA1WnpuU09NUnpzCnZuZDFjTnhlYnZHbkJNQnlKb0FS
            VEx1MlJZMnBXcHgyd241Z2xnTGQyaFkKLS0tIHhTZTNnWVIrcXhTVlI2OVgvYzNM
            Y21OM2FyaE5LS0lDWko5UllLbWQ3SnMKRscbyQSNjBE1WI3FV38Wpyi36HQANizP
            a1L5xPohddQJ4qfdZ19Swxd0JaSeAisY6ZF/7hVcCV4mcuHVT+rFdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T21:52:34Z"
    mac: ENC[AES256_GCM,data:Ly2C6IAHVErrubKYi2CNL3z5wtGcTmmbpHdRiP4e7Rcc8/SN0QptXiStuEK+/PrQtpWIVPQjrBCKz75cD+hF86GTYyU8uhSD74mX+/BNKnTE/j38CREsqnerDv68tIPWUhBmI8jx3M7Q504tmEAQZ7MbZalLU1XRU+fGVHH8/3o=,iv:qMQvngn9YCAmOvytWvRSyGmkGbPIbSWxhmpUUKdzFsA=,tag:H1DoEdJ882pqyt5y3rdsFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
