apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.appName }}-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: user-apps
  sources:
    - repoURL: https://github.com/okccl/platform-charts.git
      targetRevision: main
      path: charts/generic-frontend
      helm:
        valueFiles:
          - $values/apps/${{ values.appName }}-frontend/values.yaml
    - repoURL: https://github.com/okccl/platform-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/okccl/platform-gitops.git
      targetRevision: main
      path: apps/${{ values.appName }}-frontend/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.appName }}
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.parentRefs[].group
        - .spec.parentRefs[].kind
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
