apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-db
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: local-path-retain
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: backstage-db-credentials
      postInitSQL:
        - ALTER ROLE app CREATEDB;
  backup:
    barmanObjectStore:
      endpointURL: "http://host.k3d.internal:9000"
      destinationPath: "s3://cnpg-backup/backstage-db"
      s3Credentials:
        accessKeyId:
          name: minio-backup-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-backup-secret
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "7d"
  monitoring:
    enablePodMonitor: true
