apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: ghcr-token
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  appID: "3638469"
  installID: "131473848"
  auth:
    privateKey:
      secretRef:
        name: backstage-secret
        key: GITHUB_APP_PRIVATE_KEY
  permissions:
    packages: read
