app:
  name: ${{ values.appName }}-backend
image:
  repository: ghcr.io/okccl/${{ values.appName }}-backend
  tag: latest
containerPort: 8000
db:
  enabled: ${{ values.withDb }}
  name: ${{ values.appName }}-db
  instances: 1
  postgresVersion: 17
  storageSize: 1Gi
